on: push
jobs: 
    second-job: 
       runs-on: ubantu-latest
       steps: 
          - run: node --version
          - run: npm --version
          - uses: actions/checkout@v3
          - run: node index.js
